image: Visual Studio 2017
init:
  - git clone --recursive https://github.com/9chu/LuaSTGPlus C:\projects\LuaSTGPlus
  - git clone --recursive https://github.com/9chu/fancy2d C:\projects\fancy2d
before_build:
  - cd C:\projects\fancy2d
  - msbuild /p:Configuration=Release;Platform="Any CPU" fancylib\fancylib.vcxproj 
  - msbuild /p:Configuration=Release;Platform="Any CPU" fancy2D\fancy2D.vcxproj
  - cd ..\LuaSTGPlus
  - cd 3rdparty\luajit
  - mkdir _build
  - cd _build
  - cmake -G "Visual Studio 12" -DLUAJIT_ENABLE_LUA52COMPAT=false ..
  - msbuild luajit.sln /t:Rebuild /p:Configuration=Release;Platform="Any CPU"
  - cd ..\..\..
build_script:
  - cd C:\projects\LuaSTGPlus
  - msbuild LuaSTGPlus.sln /p:Configuration=Release_dev;Platform="Any CPU" 
